### ISSUE TITLE
Выставление счета на оплату.

### ISSUE THREAD

**Issue by piton66** [begateway/begateway-api-php#15]
Добрый день. 
Подскажите какой алгоритм выставления счета на оплату покупателю. 
Выставлять будем счет будем по нажатию кнопки в 1С. 
Как добавить тестовый набор данных?

**Comment by piton66** [comment]
Тестовый платеж вроде норм возвращает. Но на почту сообщение не приходит. Может это потому что тестового набора данных нет?
А если поменять  service_no на номер нашего заказа то возвращает ошибку
{"message":"Gateway not found.","errors":{"system":["System error."]}}

**Comment by avsh** [comment]
От какого магазина тестируете? И на почту ожидаете подтверждение оплаты как покупатель?
