### ISSUE TITLE
Public keys for test shops

### ISSUE THREAD

**Issue by pro2s** [begateway/begateway-api-php#28]
Hi,

Where can I find the public keys for test shops to verify the signature of the webhook request?

https://doc.begateway.com/en/webhooks
Test shops:
Shop without 3-D Secure
Shop Id 361
Shop secret key b8647b68898b084b836474ed8d61ffe117c9a01168d867f24953b776ddcb134d
Shop with 3-D Secure
Shop Id 362
Shop secret key 9ad8ad735945919845b9a1996af72d886ab43d3375502256dbf8dd16bca59a4e

Thanks

**Comment by avsh** [comment]
Hi!

Check the new 4.4.2 release. Test public keys were published.
