### ISSUE TITLE
How to create a payment subscription (recurring payments)?

### ISSUE THREAD

**Issue by jukuan** [begateway/begateway-api-php#34]
Is that possible?
I mean the subscription from your documentation: https://docs.bepaid.by/en/subscriptions/subscriptions#create-subscription

Should I create a transaction for that?  (like `$transaction = new \BeGateway\GetPaymentToken;`)

Thanks for your package and for possible help in advance.

**Comment by avsh** [comment]
Hello!

It will require the library update to introduce plans and subscriptions. Let me check what I can do here and when.

**Comment by jukuan** [comment]
@avsh  thanks for response.
Nevermind. I've created my custom library for or any custom request (subscription too): https://github.com/jukuan/bepaid-acquiring. It's a draft yet. (it's based on my library for other payment provider, i just changed that for bePaid).
I was inspired by your library , but i need to customize curl options and i like to work with DTOs. But that's my plan for the future.

When and if i have time, I will create a pull-request to your package probably.

Thank you for quick support.

**Comment by avsh** [comment]
you are welcome. look forward your PR :)
